// Datos simulados de la tienda pública. Misma jerarquía del catálogo real de
// Praga Medellín (categoría > subcategoría > tallas). Cuando el backend exista,
// estos datos solo se usan con VITE_USE_MOCK=true.

const TALLAS_ROPA = ['S', 'M', 'L', 'XL', '2XL']
const TALLAS_TENIS = ['7-40', '8-41', '9-42', '10-43', '11-44']
const TALLAS_CHANCLAS = ['6-39', '7-40', '8-41', '9-42', '10-43', '11-44']

export const categorias = [
  { id: 1, nombre: 'Bolsos', catalogo: 'hombre' },
  { id: 2, nombre: 'Buzos', catalogo: 'hombre' },
  { id: 3, nombre: 'Camisetas', catalogo: 'hombre' },
  { id: 4, nombre: 'Chanclas', catalogo: 'hombre' },
  { id: 5, nombre: 'Conjuntos', catalogo: 'hombre' },
  { id: 6, nombre: 'Gorras', catalogo: 'hombre' },
  { id: 7, nombre: 'Jeans', tallas: ['30', '32', '34', '36', '38'], catalogo: 'hombre' },
  { id: 8, nombre: 'Mochos', tallas: ['28', '30', '32', '34', '36', '38'], catalogo: 'hombre' },
  { id: 9, nombre: 'Pantalonetas', tallas: ['L', 'M', 'XL', '2XL'], catalogo: 'hombre' },
  { id: 10, nombre: 'Perfumes', catalogo: 'hombre' },
  { id: 11, nombre: 'Sudaderas', catalogo: 'hombre' },
  { id: 12, nombre: 'Tenis', catalogo: 'hombre' },

  // Catálogo Mujer
  { id: 13, nombre: 'Blusas', tallas: ['XS/S', 'S/M', 'M/L'], catalogo: 'mujer' },
  { id: 14, nombre: 'Blusones cortos', tallas: ['S', 'M', 'L'], catalogo: 'mujer' },
  { id: 15, nombre: 'Blusones', tallas: ['S', 'M', 'L'], catalogo: 'mujer' },
  { id: 16, nombre: 'Bodys', tallas: ['S/M', 'M/L', 'Talla única'], catalogo: 'mujer' },
  { id: 17, nombre: 'Bolsos', catalogo: 'mujer' },
  { id: 18, nombre: 'Chanclas', tallas: ['5', '6', '7', '8'], catalogo: 'mujer' },
  { id: 19, nombre: 'Conjuntos', tallas: ['S', 'M', 'L'], catalogo: 'mujer' },
  { id: 20, nombre: 'Sets', tallas: ['XS', 'S', 'M', 'Talla única'], catalogo: 'mujer' },
  { id: 21, nombre: 'Faldas', tallas: ['XS', 'S', 'M', 'L', 'XL'], catalogo: 'mujer' },
  { id: 22, nombre: 'Jeans', tallas: ['01-6', '03-8', '05-10', '07-12', '09-14', '11-16'], catalogo: 'mujer' },
  { id: 23, nombre: 'Perfumes', catalogo: 'mujer' },
  { id: 24, nombre: 'Relojes', catalogo: 'mujer' },
  { id: 25, nombre: 'Chaquetas', tallas: ['L', 'XL'], catalogo: 'mujer' },
  { id: 26, nombre: 'Shorts', tallas: ['XS', 'S', 'M'], catalogo: 'mujer' },
  { id: 27, nombre: 'Vestidos', tallas: ['S', 'M', 'L'], catalogo: 'mujer' },
  { id: 28, nombre: 'Tenis', catalogo: 'mujer' },
]

export const subcategorias = [
  { id: 1, categoria_id: 1, nombre: 'Bolsos Premium 1.1', tallas: [] },
  { id: 2, categoria_id: 1, nombre: 'Bolsos Turcos', tallas: [] },
  { id: 3, categoria_id: 2, nombre: 'Buzos Premium 1.1', tallas: TALLAS_ROPA },
  { id: 4, categoria_id: 2, nombre: 'Buzos Turcos', tallas: TALLAS_ROPA },
  { id: 5, categoria_id: 3, nombre: 'Camisetas Originales', tallas: TALLAS_ROPA },
  { id: 6, categoria_id: 3, nombre: 'Camisetas Premium 1.1', tallas: TALLAS_ROPA },
  { id: 7, categoria_id: 3, nombre: 'Camisetas Turcas', tallas: TALLAS_ROPA },
  { id: 8, categoria_id: 4, nombre: 'Chanclas Premium 1.1', tallas: TALLAS_CHANCLAS },
  { id: 9, categoria_id: 4, nombre: 'Chanclas Turcas', tallas: TALLAS_CHANCLAS },
  { id: 10, categoria_id: 5, nombre: 'Conjuntos Premium 1.1', tallas: TALLAS_ROPA },
  { id: 11, categoria_id: 5, nombre: 'Conjuntos Turcos', tallas: TALLAS_ROPA },
  { id: 12, categoria_id: 6, nombre: 'Gorras Originales', tallas: [] },
  { id: 13, categoria_id: 6, nombre: 'Gorras Premium 1.1', tallas: [] },
  { id: 14, categoria_id: 6, nombre: 'Gorras Turcas', tallas: [] },
  { id: 15, categoria_id: 10, nombre: 'Perfumes Originales', tallas: [] },
  { id: 16, categoria_id: 10, nombre: 'Perfumes Premium 1.1', tallas: [] },
  { id: 17, categoria_id: 11, nombre: 'Sudaderas Premium 1.1', tallas: TALLAS_ROPA },
  { id: 18, categoria_id: 12, nombre: 'Tenis Originales', tallas: TALLAS_TENIS },
  { id: 19, categoria_id: 12, nombre: 'Tenis Premium 1.1', tallas: TALLAS_TENIS },
  { id: 20, categoria_id: 12, nombre: 'Tenis Turcos', tallas: TALLAS_TENIS },

  // Catálogo Mujer
  { id: 21, categoria_id: 23, nombre: 'Perfumes Calidad 1.1', tallas: [] },
  { id: 22, categoria_id: 28, nombre: 'Tenis Calidad 1.1', tallas: ['5', '6', '7', '8'] },
  { id: 23, categoria_id: 28, nombre: 'Tenis Calidad Turca', tallas: ['5', '6', '7'] },
  { id: 24, categoria_id: 28, nombre: 'Tenis Originales', tallas: ['5', '6', '7'] },
]

// Productos con sus VARIANTES (talla + stock disponible para la tienda).
// `destacado: true` los muestra en la portada.
export const productos = [
  {
    id: 1,
    nombre: 'Buzo Premium 1.1 Negro',
    descripcion: 'Buzo premium de algodón con capucha y estampado 1.1. Ajuste cómodo, tela de alta densidad.',
    precio: 159000,
    imagen_url: '/images/products/chaqueta.svg',
    categoria_id: 2,
    subcategoria_id: 3,
    destacado: true,
    variantes: TALLAS_ROPA.map((t) => ({ talla: t, stock: 6 })),
  },
  {
    id: 2,
    nombre: 'Buzo Turco Gris',
    descripcion: 'Buzo turco de tela suave y liviana, ideal para el día a día.',
    precio: 129000,
    imagen_url: '/images/products/chaqueta.svg',
    categoria_id: 2,
    subcategoria_id: 4,
    destacado: false,
    variantes: TALLAS_ROPA.map((t) => ({ talla: t, stock: 4 })),
  },
  {
    id: 3,
    nombre: 'Camiseta Original Negra',
    descripcion: 'Camiseta básica de algodón 100%, corte clásico. La de todos los días.',
    precio: 85000,
    imagen_url: '/images/products/camiseta.svg',
    categoria_id: 3,
    subcategoria_id: 5,
    destacado: true,
    variantes: TALLAS_ROPA.map((t) => ({ talla: t, stock: 8 })),
  },
  {
    id: 4,
    nombre: 'Camiseta Premium 1.1 Boxeada',
    descripcion: 'Manga boxeada, estampado 1.1. Edición limitada de la línea premium.',
    precio: 99000,
    imagen_url: '/images/products/camiseta.svg',
    categoria_id: 3,
    subcategoria_id: 6,
    destacado: true,
    variantes: TALLAS_ROPA.map((t) => ({ talla: t, stock: 5 })),
  },
  {
    id: 5,
    nombre: 'Camiseta Turca Básica',
    descripcion: 'Camiseta turca de corte clásico, tela con caída ligera.',
    precio: 75000,
    imagen_url: '/images/products/camiseta.svg',
    categoria_id: 3,
    subcategoria_id: 7,
    destacado: false,
    variantes: TALLAS_ROPA.map((t) => ({ talla: t, stock: 3 })),
  },
  {
    id: 6,
    nombre: 'Chancla Premium 1.1',
    descripcion: 'Chancla premium con logo 1.1, suela cómoda y antideslizante.',
    precio: 45000,
    imagen_url: '/images/products/accesorio.svg',
    categoria_id: 4,
    subcategoria_id: 8,
    destacado: true,
    variantes: TALLAS_CHANCLAS.map((t) => ({ talla: t, stock: 7 })),
  },
  {
    id: 7,
    nombre: 'Conjunto Premium 1.1',
    descripcion: 'Conjunto de dos piezas de la línea premium 1.1. Tela de alta calidad.',
    precio: 219000,
    imagen_url: '/images/products/chaqueta.svg',
    categoria_id: 5,
    subcategoria_id: 10,
    destacado: true,
    variantes: TALLAS_ROPA.map((t) => ({ talla: t, stock: 4 })),
  },
  {
    id: 8,
    nombre: 'Gorra Original Negra',
    descripcion: 'Gorra negra con bordado frontal de la marca. Talla única ajustable.',
    precio: 60000,
    imagen_url: '/images/products/accesorio.svg',
    categoria_id: 6,
    subcategoria_id: 12,
    destacado: false,
    variantes: [{ talla: null, stock: 12 }],
  },
  {
    id: 9,
    nombre: 'Jean Cargo Negro',
    descripcion: 'Jean cargo de corte recto con bolsillos laterales. Denim resistente.',
    precio: 139000,
    imagen_url: '/images/products/pantalon.svg',
    categoria_id: 7,
    subcategoria_id: null,
    destacado: true,
    variantes: ['30', '32', '34', '36', '38'].map((t) => ({ talla: t, stock: 5 })),
  },
  {
    id: 10,
    nombre: 'Mocho Pata de Gallo',
    descripcion: 'Pantalón mocho con estampado pata de gallo, corte cómodo.',
    precio: 149000,
    imagen_url: '/images/products/pantalon.svg',
    categoria_id: 8,
    subcategoria_id: null,
    destacado: false,
    variantes: ['28', '30', '32', '34', '36', '38'].map((t) => ({ talla: t, stock: 3 })),
  },
  {
    id: 11,
    nombre: 'Pantaloneta Deportiva',
    descripcion: 'Pantaloneta corta deportiva, ideal para entrenar.',
    precio: 95000,
    imagen_url: '/images/products/pantalon.svg',
    categoria_id: 9,
    subcategoria_id: null,
    destacado: false,
    variantes: ['L', 'M', 'XL', 'XXL'].map((t) => ({ talla: t, stock: 6 })),
  },
  {
    id: 12,
    nombre: 'Perfume Original 1.1',
    descripcion: 'Perfume edición original de la marca. Presentación única.',
    precio: 159000,
    imagen_url: '/images/products/accesorio.svg',
    categoria_id: 10,
    subcategoria_id: 15,
    destacado: true,
    variantes: [{ talla: null, stock: 9 }],
  },
  {
    id: 13,
    nombre: 'Sudadera Premium 1.1',
    descripcion: 'Sudadera con capucha, bolsillo canguro y estampado premium 1.1.',
    precio: 169000,
    imagen_url: '/images/products/chaqueta.svg',
    categoria_id: 11,
    subcategoria_id: 17,
    destacado: true,
    variantes: TALLAS_ROPA.map((t) => ({ talla: t, stock: 5 })),
  },
  {
    id: 14,
    nombre: 'Tenis Original Blanco',
    descripcion: 'Tenis blanco de corte original. Cómodo y versátil.',
    precio: 189000,
    imagen_url: '/images/products/chaqueta.svg',
    categoria_id: 12,
    subcategoria_id: 18,
    destacado: true,
    variantes: TALLAS_TENIS.map((t) => ({ talla: t, stock: 6 })),
  },
  {
    id: 15,
    nombre: 'Bolso Premium 1.1',
    descripcion: 'Bolso premium con logo de la marca. Ideal para el día a día.',
    precio: 120000,
    imagen_url: '/images/products/accesorio.svg',
    categoria_id: 1,
    subcategoria_id: 1,
    destacado: false,
    variantes: [{ talla: null, stock: 10 }],
  },
  {
    id: 16,
    nombre: 'Blusa Seda',
    descripcion: 'Blusa de seda, suave y ligera. Perfecta para el día a día.',
    precio: 65000,
    imagen_url: '/images/products/camiseta.svg',
    categoria_id: 13,
    subcategoria_id: null,
    destacado: true,
    variantes: ['XS/S', 'S/M', 'M/L'].map((t) => ({ talla: t, stock: 5 })),
  },
  {
    id: 17,
    nombre: 'Jeans Mujer',
    descripcion: 'Jeans de corte cómodo. Tallas dobles (colombiana - US).',
    precio: 129000,
    imagen_url: '/images/products/pantalon.svg',
    categoria_id: 22,
    subcategoria_id: null,
    destacado: false,
    variantes: ['01-6', '03-8', '05-10', '07-12', '09-14', '11-16'].map((t) => ({ talla: t, stock: 4 })),
  },
  {
    id: 18,
    nombre: 'Vestido Elegante',
    descripcion: 'Vestido elegante de mujer, corte favorecedor.',
    precio: 149000,
    imagen_url: '/images/products/camiseta.svg',
    categoria_id: 27,
    subcategoria_id: null,
    destacado: true,
    variantes: ['S', 'M', 'L'].map((t) => ({ talla: t, stock: 3 })),
  },
]